In [1]:
import pandas as pd

In [2]:
import os 
print(os.getcwd())

D:\ML_Projects\Mental_Health\notebook

In [3]:
data = pd.read_csv("../data/raw/MentalHealthScreeningTest_Report_AllEntries.csv")

In [4]:
data.head()

,Name,Email,Phone,Age,Gender,Branch,Division,Have you recently been able to concentrate on whatever you're doing?,Have you recently lost much sleep over worry ?,Have you recently felt that you were playing a useful part in things?,...,I tend to bounce back quickly after hard times,I have a hard time making it through stressful events.,It does not take me long to recover from a stressful event.,It is hard for me to snap back when something bad happens.,I usually come through difficult times with little trouble.,I tend to take a long time to get over set-backs in my life.,BRS Score,Added Time,Referrer Name,Task Owner
0,"SANAY, SURANA",SANAY.1251070902@VIT.EDU,9518594104,19,Male,Computer Science,J,Better than usual,Rather more than usual,Much less than usual,...,Disagree,Agree,Disagree,Agree,Neutral,Neutral,2.33,17-Oct-2025 19:22:56,NaN,sujaykarad2005@gmail.com
1,"Shreya, Singh Senger",shreya.1251090244@vit.edu,9435637192,17,Female,CSE(Artificial Intelligence),F,Less than usual,No more than usual,Less so than usual,...,Disagree,Agree,Disagree,Strongly Agree,Neutral,Strongly Agree,1.83,17-Oct-2025 17:01:53,NaN,sujaykarad2005@gmail.com
2,"Ishan, Sahu",ishan.1251070277@vit.edu,7498446313,18,Male,Computer Science,E,Less than usual,Not at all,Less so than usual,...,NaN,NaN,NaN,NaN,NaN,NaN,0.00,15-Oct-2025 20:22:23,android-app://com.google.android.gm/,sujaykarad2005@gmail.com
3,"Dhruv, Thorat",dhruv.thorat27@gmail.com,9156130830,18,Male,Mechanical Engineering,B,Same as usual,Rather more than usual,Same as usual,...,NaN,NaN,NaN,NaN,NaN,NaN,0.00,15-Oct-2025 17:19:41,NaN,sujaykarad2005@gmail.com
4,"Ojas, Dongre",ojas.1251010723@vit.edu,9373978147,18,Male,Artificial Intelligence and Data Science,D,Same as usual,Not at all,Same as usual,...,NaN,NaN,NaN,NaN,NaN,NaN,0.00,15-Oct-2025 16:12:43,NaN,sujaykarad2005@gmail.com

In [5]:
data.columns

Index(['Name', 'Email', 'Phone', 'Age', 'Gender', 'Branch', 'Division',
       'Have you recently been able to concentrate on whatever you're doing?',
       'Have you recently lost much sleep over worry ?',
       'Have you recently felt that you were playing a useful part in things?',
       'Have you recently felt capable of making decisions about things?',
       'Have you recently felt constantly under strain?',
       'Have you recently been able to enjoy your normal day-to-day activities?',
       'Have you recently been able to face up to problems?',
       'Have you recently felt you couldn't overcome your difficulties?',
       'Have you recently been feeling unhappy or depressed?',
       'Have you recently been losing confidence in yourself?',
       'Have you recently been thinking of yourself as a worthless person?',
       'Have you recently been feeling reasonably happy, all things considered?',
       'GHQ Score', 'I found it hard to wind down',
       'I was aware of dryness of my mouth',
       'I couldn’t seem to experience any positive feeling at all',
       'I experienced breathing difficulty (e.g. excessively rapid breathing, breathlessness in the absence of physical exertion)',
       'I found it difficult to work up the initiative to do things',
       'I tended to over-react to situations',
       'I experienced trembling (e.g. in the hands)', 'Total Score (DASSD-I)',
       'I was worried about situations in which I might panic and make a fool of myself',
       'I found it difficult to relax',
       'I felt that I was using a lot of nervous energy',
       'I felt that I had nothing to look forward to',
       'I found myself getting agitated', 'I felt down-hearted and blue',
       'I was intolerant of anything that kept me from getting on with what I was doing',
       'Total Score (DASSD-II)', 'I felt I was close to panic',
       'I was unable to become enthusiastic about anything',
       'I felt I wasn’t worth much as a person',
       'I was aware of the action of my heart in the absence of physical exertion (e.g. sense of heart rate increase, heart missing a beat)',
       'I felt that I was rather touchy',
       'I felt scared without any good reason',
       'I felt that life was meaningless', 'Total Score (DASSD-III)',
       'I tend to bounce back quickly after hard times',
       'I have a hard time making it through stressful events.',
       'It does not take me long to recover from a stressful event.',
       'It is hard for me to snap back when something bad happens.',
       'I usually come through difficult times with little trouble.',
       'I tend to take a long time to get over set-backs in my life.',
       'BRS Score', 'Added Time', 'Referrer Name', 'Task Owner'],
      dtype='object')

In [6]:
data.shape

(3258, 54)

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3258 entries, 0 to 3257
Data columns (total 54 columns):
 #   Column                                                                                                                               Non-Null Count  Dtype
---  ------                                                                                                                               --------------  -----
 0   Name                                                                                                                                 3258 non-null   object
 1   Email                                                                                                                                3258 non-null   object
 2   Phone                                                                                                                                3258 non-null   int64
 3   Age                                                                                                                                  3258 non-null   int64
 4   Gender                                                                                                                               3258 non-null   object
 5   Branch                                                                                                                               3258 non-null   object
 6   Division                                                                                                                             3258 non-null   object
 7   Have you recently been able to concentrate on whatever you're doing?                                                                 3258 non-null   object
 8   Have you recently lost much sleep over worry ?                                                                                       3258 non-null   object
 9   Have you recently felt that you were playing a useful part in things?                                                                3258 non-null   object
 10  Have you recently felt capable of making decisions about things?                                                                     3258 non-null   object
 11  Have you recently felt constantly under strain?                                                                                      3258 non-null   object
 12  Have you recently been able to enjoy your normal day-to-day activities?                                                              3258 non-null   object
 13  Have you recently been able to face up to problems?                                                                                  3258 non-null   object
 14  Have you recently felt you couldn't overcome your difficulties?                                                                      3258 non-null   object
 15  Have you recently been feeling unhappy or depressed?                                                                                 3258 non-null   object
 16  Have you recently been losing confidence in yourself?                                                                                3258 non-null   object
 17  Have you recently been thinking of yourself as a worthless person?                                                                   3258 non-null   object
 18  Have you recently been feeling reasonably happy, all things considered?                                                              3258 non-null   object
 19  GHQ Score                                                                                                                            3258 non-null   int64
 20  I found it hard to wind down                                                                                                         1107 non-null   object
 21  I was aware of dryness of my mouth                                                                                                   1107 non-null   object
 22  I couldn’t seem to experience any positive feeling at all                                                                            1107 non-null   object
 23  I experienced breathing difficulty (e.g. excessively rapid breathing, breathlessness in the absence of physical exertion)            1107 non-null   object
 24  I found it difficult to work up the initiative to do things                                                                          1107 non-null   object
 25  I tended to over-react to situations                                                                                                 1107 non-null   object
 26  I experienced trembling (e.g. in the hands)                                                                                          1107 non-null   object
 27  Total Score (DASSD-I)                                                                                                                3258 non-null   int64
 28  I was worried about situations in which I might panic and make a fool of myself                                                      1107 non-null   object
 29  I found it difficult to relax                                                                                                        1107 non-null   object
 30  I felt that I was using a lot of nervous energy                                                                                      1107 non-null   object
 31  I felt that I had nothing to look forward to                                                                                         1107 non-null   object
 32  I found myself getting agitated                                                                                                      1107 non-null   object
 33  I felt down-hearted and blue                                                                                                         1107 non-null   object
 34  I was intolerant of anything that kept me from getting on with what I was doing                                                      1107 non-null   object
 35  Total Score (DASSD-II)                                                                                                               3258 non-null   int64
 36  I felt I was close to panic                                                                                                          1107 non-null   object
 37  I was unable to become enthusiastic about anything                                                                                   1107 non-null   object
 38  I felt I wasn’t worth much as a person                                                                                               1107 non-null   object
 39  I was aware of the action of my heart in the absence of physical exertion (e.g. sense of heart rate increase, heart missing a beat)  1107 non-null   object
 40  I felt that I was rather touchy                                                                                                      1107 non-null   object
 41  I felt scared without any good reason                                                                                                1107 non-null   object
 42  I felt that life was meaningless                                                                                                     1107 non-null   object
 43  Total Score (DASSD-III)                                                                                                              3258 non-null   int64
 44  I tend to bounce back quickly after hard times                                                                                       1107 non-null   object
 45  I have a hard time making it through stressful events.                                                                               1107 non-null   object
 46  It does not take me long to recover from a stressful event.                                                                          1107 non-null   object
 47  It is hard for me to snap back when something bad happens.                                                                           1107 non-null   object
 48  I usually come through difficult times with little trouble.                                                                          1107 non-null   object
 49  I tend to take a long time to get over set-backs in my life.                                                                         1107 non-null   object
 50  BRS Score                                                                                                                            3258 non-null   float64
 51  Added Time                                                                                                                           3258 non-null   object
 52  Referrer Name                                                                                                                        2881 non-null   object
 53  Task Owner                                                                                                                           3258 non-null   object
dtypes: float64(1), int64(6), object(47)
memory usage: 1.3+ MB

In [8]:
data.describe()

,Phone,Age,GHQ Score,Total Score (DASSD-I),Total Score (DASSD-II),Total Score (DASSD-III),BRS Score
count,3.258000e+03,3.258000e+03,3258.000000,3258.000000,3258.000000,3258.000000,3258.000000
mean,1.071011e+10,2.842759e+06,10.324739,4.345611,4.727440,3.788828,1.017342
std,4.225033e+10,1.616468e+08,5.793934,7.657362,8.473549,7.286048,1.448837
min,1.234560e+05,5.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
25%,8.007145e+09,1.800000e+01,6.000000,0.000000,0.000000,0.000000,0.000000
50%,8.888822e+09,1.800000e+01,9.000000,0.000000,0.000000,0.000000,0.000000
75%,9.370515e+09,1.800000e+01,13.000000,8.000000,8.000000,4.000000,2.670000
max,9.199981e+11,9.226596e+09,36.000000,42.000000,42.000000,42.000000,5.000000

In [9]:
data.isnull().sum()

Name                                                                                                                                      0
Email                                                                                                                                     0
Phone                                                                                                                                     0
Age                                                                                                                                       0
Gender                                                                                                                                    0
Branch                                                                                                                                    0
Division                                                                                                                                  0
Have you recently been able to concentrate on whatever you're doing?                                                                      0
Have you recently lost much sleep over worry ?                                                                                            0
Have you recently felt that you were playing a useful part in things?                                                                     0
Have you recently felt capable of making decisions about things?                                                                          0
Have you recently felt constantly under strain?                                                                                           0
Have you recently been able to enjoy your normal day-to-day activities?                                                                   0
Have you recently been able to face up to problems?                                                                                       0
Have you recently felt you couldn't overcome your difficulties?                                                                           0
Have you recently been feeling unhappy or depressed?                                                                                      0
Have you recently been losing confidence in yourself?                                                                                     0
Have you recently been thinking of yourself as a worthless person?                                                                        0
Have you recently been feeling reasonably happy, all things considered?                                                                   0
GHQ Score                                                                                                                                 0
I found it hard to wind down                                                                                                           2151
I was aware of dryness of my mouth                                                                                                     2151
I couldn’t seem to experience any positive feeling at all                                                                              2151
I experienced breathing difficulty (e.g. excessively rapid breathing, breathlessness in the absence of physical exertion)              2151
I found it difficult to work up the initiative to do things                                                                            2151
I tended to over-react to situations                                                                                                   2151
I experienced trembling (e.g. in the hands)                                                                                            2151
Total Score (DASSD-I)                                                                                                                     0
I was worried about situations in which I might panic and make a fool of myself                                                        2151
I found it difficult to relax                                                                                                          2151
I felt that I was using a lot of nervous energy                                                                                        2151
I felt that I had nothing to look forward to                                                                                           2151
I found myself getting agitated                                                                                                        2151
I felt down-hearted and blue                                                                                                           2151
I was intolerant of anything that kept me from getting on with what I was doing                                                        2151
Total Score (DASSD-II)                                                                                                                    0
I felt I was close to panic                                                                                                            2151
I was unable to become enthusiastic about anything                                                                                     2151
I felt I wasn’t worth much as a person                                                                                                 2151
I was aware of the action of my heart in the absence of physical exertion (e.g. sense of heart rate increase, heart missing a beat)    2151
I felt that I was rather touchy                                                                                                        2151
I felt scared without any good reason                                                                                                  2151
I felt that life was meaningless                                                                                                       2151
Total Score (DASSD-III)                                                                                                                   0
I tend to bounce back quickly after hard times                                                                                         2151
I have a hard time making it through stressful events.                                                                                 2151
It does not take me long to recover from a stressful event.                                                                            2151
It is hard for me to snap back when something bad happens.                                                                             2151
I usually come through difficult times with little trouble.                                                                            2151
I tend to take a long time to get over set-backs in my life.                                                                           2151
BRS Score                                                                                                                                 0
Added Time                                                                                                                                0
Referrer Name                                                                                                                           377
Task Owner                                                                                                                                0
dtype: int64

In [10]:
data.isna().sum()

Name                                                                                                                                      0
Email                                                                                                                                     0
Phone                                                                                                                                     0
Age                                                                                                                                       0
Gender                                                                                                                                    0
Branch                                                                                                                                    0
Division                                                                                                                                  0
Have you recently been able to concentrate on whatever you're doing?                                                                      0
Have you recently lost much sleep over worry ?                                                                                            0
Have you recently felt that you were playing a useful part in things?                                                                     0
Have you recently felt capable of making decisions about things?                                                                          0
Have you recently felt constantly under strain?                                                                                           0
Have you recently been able to enjoy your normal day-to-day activities?                                                                   0
Have you recently been able to face up to problems?                                                                                       0
Have you recently felt you couldn't overcome your difficulties?                                                                           0
Have you recently been feeling unhappy or depressed?                                                                                      0
Have you recently been losing confidence in yourself?                                                                                     0
Have you recently been thinking of yourself as a worthless person?                                                                        0
Have you recently been feeling reasonably happy, all things considered?                                                                   0
GHQ Score                                                                                                                                 0
I found it hard to wind down                                                                                                           2151
I was aware of dryness of my mouth                                                                                                     2151
I couldn’t seem to experience any positive feeling at all                                                                              2151
I experienced breathing difficulty (e.g. excessively rapid breathing, breathlessness in the absence of physical exertion)              2151
I found it difficult to work up the initiative to do things                                                                            2151
I tended to over-react to situations                                                                                                   2151
I experienced trembling (e.g. in the hands)                                                                                            2151
Total Score (DASSD-I)                                                                                                                     0
I was worried about situations in which I might panic and make a fool of myself                                                        2151
I found it difficult to relax                                                                                                          2151
I felt that I was using a lot of nervous energy                                                                                        2151
I felt that I had nothing to look forward to                                                                                           2151
I found myself getting agitated                                                                                                        2151
I felt down-hearted and blue                                                                                                           2151
I was intolerant of anything that kept me from getting on with what I was doing                                                        2151
Total Score (DASSD-II)                                                                                                                    0
I felt I was close to panic                                                                                                            2151
I was unable to become enthusiastic about anything                                                                                     2151
I felt I wasn’t worth much as a person                                                                                                 2151
I was aware of the action of my heart in the absence of physical exertion (e.g. sense of heart rate increase, heart missing a beat)    2151
I felt that I was rather touchy                                                                                                        2151
I felt scared without any good reason                                                                                                  2151
I felt that life was meaningless                                                                                                       2151
Total Score (DASSD-III)                                                                                                                   0
I tend to bounce back quickly after hard times                                                                                         2151
I have a hard time making it through stressful events.                                                                                 2151
It does not take me long to recover from a stressful event.                                                                            2151
It is hard for me to snap back when something bad happens.                                                                             2151
I usually come through difficult times with little trouble.                                                                            2151
I tend to take a long time to get over set-backs in my life.                                                                           2151
BRS Score                                                                                                                                 0
Added Time                                                                                                                                0
Referrer Name                                                                                                                           377
Task Owner                                                                                                                                0
dtype: int64

# Data Cleaning

In [11]:
# Select Only required columns 
req_columns = ["Age","Gender","Branch","GHQ Score","Total Score (DASSD-I)","Total Score (DASSD-II)","Total Score (DASSD-III)","BRS Score"]

In [12]:
# dataframe with required columns 
sub_data = data[req_columns].copy()

In [13]:
sub_data.head()

,Age,Gender,Branch,GHQ Score,Total Score (DASSD-I),Total Score (DASSD-II),Total Score (DASSD-III),BRS Score
0,19,Male,Computer Science,21,16,12,16,2.33
1,17,Female,CSE(Artificial Intelligence),18,14,18,10,1.83
2,18,Male,Computer Science,9,0,0,0,0.00
3,18,Male,Mechanical Engineering,10,0,0,0,0.00
4,18,Male,Artificial Intelligence and Data Science,3,0,0,0,0.00

In [14]:
sub_data.isna().sum()

Age                        0
Gender                     0
Branch                     0
GHQ Score                  0
Total Score (DASSD-I)      0
Total Score (DASSD-II)     0
Total Score (DASSD-III)    0
BRS Score                  0
dtype: int64

In [15]:
sub_data[sub_data["BRS Score"]==0]

,Age,Gender,Branch,GHQ Score,Total Score (DASSD-I),Total Score (DASSD-II),Total Score (DASSD-III),BRS Score
2,18,Male,Computer Science,9,0,0,0,0.0
3,18,Male,Mechanical Engineering,10,0,0,0,0.0
4,18,Male,Artificial Intelligence and Data Science,3,0,0,0,0.0
6,18,Male,CSE(Artificial Intelligence),1,0,0,0,0.0
7,18,Male,Artificial Intelligence and Data Science,3,0,0,0,0.0
...,...,...,...,...,...,...,...,...
3252,18,Female,Electronics and Telecommunication,11,0,0,0,0.0
3253,20,Male,CSE(AI & ML),9,0,0,0,0.0
3254,19,Female,Computer Science,9,0,0,0,0.0
3256,20,Male,CSE(Artificial Intelligence),10,0,0,0,0.0
3257,19,Male,CSE(AI & ML),6,0,0,0,0.0

In [16]:
sub_data["Age"].value_counts()

Age
18            2153
19             605
17             404
20              70
21               9
10               3
54               2
35               1
16               1
78               1
69               1
8                1
38               1
12012007         1
5                1
55               1
134              1
23042006         1
9226596198       1
Name: count, dtype: int64

In [17]:
sub_data["Age"] = [18 if Age not in (17,18,19,20,21) else Age for Age in sub_data["Age"]]

In [18]:
sub_data.rename(columns={
    "GHQ Score":"GHQ",
    "Total Score (DASSD-I)": "Depression",
    "Total Score (DASSD-II)": "Anxiety",
    "Total Score (DASSD-III)": "Stress",
    "BRS Score": "BRS"
},inplace=True)

In [19]:
sub_data.head()

,Age,Gender,Branch,GHQ,Depression,Anxiety,Stress,BRS
0,19,Male,Computer Science,21,16,12,16,2.33
1,17,Female,CSE(Artificial Intelligence),18,14,18,10,1.83
2,18,Male,Computer Science,9,0,0,0,0.00
3,18,Male,Mechanical Engineering,10,0,0,0,0.00
4,18,Male,Artificial Intelligence and Data Science,3,0,0,0,0.00

In [20]:
sub_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3258 entries, 0 to 3257
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Age         3258 non-null   int64
 1   Gender      3258 non-null   object
 2   Branch      3258 non-null   object
 3   GHQ         3258 non-null   int64
 4   Depression  3258 non-null   int64
 5   Anxiety     3258 non-null   int64
 6   Stress      3258 non-null   int64
 7   BRS         3258 non-null   float64
dtypes: float64(1), int64(5), object(2)
memory usage: 203.8+ KB

In [21]:
sub_data.describe()

,Age,GHQ,Depression,Anxiety,Stress,BRS
count,3258.000000,3258.000000,3258.000000,3258.000000,3258.000000,3258.000000
mean,18.112953,10.324739,4.345611,4.727440,3.788828,1.017342
std,0.638647,5.793934,7.657362,8.473549,7.286048,1.448837
min,17.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,18.000000,6.000000,0.000000,0.000000,0.000000,0.000000
50%,18.000000,9.000000,0.000000,0.000000,0.000000,0.000000
75%,18.000000,13.000000,8.000000,8.000000,4.000000,2.670000
max,21.000000,36.000000,42.000000,42.000000,42.000000,5.000000

In [22]:
sub_data.to_csv("../data/cleaned/processing.csv",index=False)